trigger:
  branches:
    include:
      - develop  # Cambia por la rama que prefieras

pool:
  vmImage: 'ubuntu-latest'

steps:
  # Utilizar la versión de Node.js directamente desde NVM
  - script: |
      curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
      source ~/.nvm/nvm.sh
      nvm install 23.10.0
      node -v
    displayName: 'Instalar Node.js v23.10.0'

  # Instalar dependencias
  - script: npm install
    displayName: 'Instalar dependencias'

  # Ejecutar pruebas (si tienes)
  - script: npm test
    displayName: 'Ejecutar pruebas'

  # Construir la aplicación Next.js
  - script: npm run build
    displayName: 'Construir aplicación'

  # Desplegar en Azure Static Web Apps
  - task: AzureStaticWebApp@0
    inputs:
      app_location: './'  # Directorio raíz de la aplicación Next.js
      output_location: 'out'  # Carpeta generada por Next.js
      azure_static_web_apps_api_token: $(deployment_token)
